### ISSUE TITLE
Username not found

### ISSUE THREAD

**Issue by DocKali** [sc1341/InstagramOSINT#12]
Hi,
I'm currently trying to test this tool but I have a problem. I try to run the tool on 2 existing Insta account but the two times the tool send a "Username not found" message...
Did I have to specify my username and pass in the tool to run it? 
Where does the error come from?
Thanks for your help!

**Comment by Kithu29** [comment]
Hi, 
I'm also facing the same issue. Kindly please give a response. Thank you :)

**Comment by Abhishek-Deshmukh** [comment]
same here, I'm suspecting this is because of the Instagram's website UI changes or something.
Any help would be appreciated, thank you.

**Comment by Manan-hellsangel62626** [comment]
I have tried on many systems same problem

**Comment by YnwaFawzy** [comment]
so. it's not a perfect solution , but it works 
i just replace these two line 
 self.description = json.loads(description.get_text())
 self.profile_meta = json.loads(more_data[3].get_text()[21:].strip(';'))
with             
            self.description = json.loads(description.string)
            self.profile_meta = json.loads(more_data[3].string[21:].strip(';'))

apparently , get_text() is returning nothing for some reason.

anyway , this is the whole file for main.py in case you need it instead of replacing manually
[main.zip](https://github.com/sc1341/InstagramOSINT/files/4711826/main.zip)

have fun

**Comment by Geoveza** [comment]
same problem

**Comment by YnwaFawzy** [comment]
@Geoveza @DjChart is my solution above not working?

**Comment by gituu4567** [comment]
everytime i put a username it shows Username xxccdd not found

**Comment by mrsilas666** [comment]
try using this method
$ sudo apt install software-properties-common
and try agian ♥

**Comment by akshaysmarty00786** [comment]
Same problem

**Comment by akshaysmarty00786** [comment]
Same problem

**Comment by spctr01** [comment]
@YnwaFawzy  still it's not working and I couldn't find the lines manually they are not in the main.py file

**Comment by spctr01** [comment]
@YnwaFawzy  still not working

**Comment by tina1998612** [comment]
not working

**Comment by mathiznogoud** [comment]
> It works thanks @YnwaFawzy!!

Mine still not working, can you provide your fixed code?

**Comment by YnwaFawzy** [comment]
@mathiznogoud did you try the file in my comment up?

**Comment by Desze** [comment]
I tried the zip and it doesn't work

**Comment by YnwaFawzy** [comment]
@Desze did you try it alone? or replaced the main.py inside with the one in the repository?

**Comment by Desze** [comment]
@YnwaFawzy I replaced the main.py in the folder 
But it still doesn't work for me.

**Comment by YnwaFawzy** [comment]
@Desze you tried by using python3 and python2, right?

**Comment by Desze** [comment]
@YnwaFawzy Yes

InstagramOSINT$ python3 main.py --username desze


██╗███╗   ██╗███████╗████████╗ █████╗  ██████╗ ██████╗  █████╗ ███╗   ███╗     ██████╗ ███████╗██╗███╗   ██╗████████╗
██║████╗  ██║██╔════╝╚══██╔══╝██╔══██╗██╔════╝ ██╔══██╗██╔══██╗████╗ ████║    ██╔═══██╗██╔════╝██║████╗  ██║╚══██╔══╝
██║██╔██╗ ██║███████╗   ██║   ███████║██║  ███╗██████╔╝███████║██╔████╔██║    ██║   ██║███████╗██║██╔██╗ ██║   ██║   
██║██║╚██╗██║╚════██║   ██║   ██╔══██║██║   ██║██╔══██╗██╔══██║██║╚██╔╝██║    ██║   ██║╚════██║██║██║╚██╗██║   ██║   
██║██║ ╚████║███████║   ██║   ██║  ██║╚██████╔╝██║  ██║██║  ██║██║ ╚═╝ ██║    ╚██████╔╝███████║██║██║ ╚████║   ██║   
╚═╝╚═╝  ╚═══╝╚══════╝   ╚═╝   ╚═╝  ╚═╝ ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝╚═╝     ╚═╝     ╚═════╝ ╚══════╝╚═╝╚═╝  ╚═══╝   ╚═╝   
                                                                                                                     


[*] Starting Scan on desze
list index out of range
Username desze not found

**Comment by YnwaFawzy** [comment]
@Desze can you zip the whole folder and send it, I'll check it after 9 hours approx. (at night).

**Comment by YnwaFawzy** [comment]
@Desze so I tried to search for your username and couldn't find it. 

are you sure this is your username?

**Comment by YnwaFawzy** [comment]
@Desze try a different username, it should work fine. 

it worked fine for me on 2 different machines with different operating systems

**Comment by YnwaFawzy** [comment]
@Desze  
So i checked your profile on the web browser , and strangely the description field doesn't  exist ( as the json schema that should represent your profile <script type="application/ld+json"> ).

a quick fix is i checked if the json schema exist by adding 
```
            if( description is not None):
              self.description = json.loads(description.string)
```
and then i divided the output into two parts ,the basic one and the description 

`
self.profile_data = {"Username": self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['username'],
                             "Followers": self.text[0], "Following": self.text[2], "Posts": self.text[4],
                             "Bio": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['biography']),
                             "profile_pic_url": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
                                                        'profile_pic_url_hd']),
                             "is_business_account": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
                                     'is_business_account']),
                             "connected_to_fb": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
                                                        'connected_fb_page']),
                             "externalurl": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['external_url']),
                             "joined_recently": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
                                                        'is_joined_recently']),
                             "business_category_name": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
                                     'business_category_name']),
                             "is_private": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_private']),
                             "is_verified": str(
                                 self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_verified'])}

`


and for the description if found 
`
        if (description is not None):
            {
             "Profile name": self.description['name'],
             "URL": self.description['mainEntityofPage']['@id'],
            }
`


it should be working fine now , you can get the new file 
[main.py.zip](https://github.com/sc1341/InstagramOSINT/files/5056036/main.py.zip)

**Comment by Desze** [comment]
@YnwaFawzy It works for me now on that guy's Instagram Instagram.com/desze 
But in mine Instagram.com/idesze doesn't work

**Comment by YnwaFawzy** [comment]
@Desze it works for m , can you do a simple pprint when the error happens 
<img width="731" alt="Screen Shot 2020-08-11 at 1 41 55 PM" src="https://user-images.githubusercontent.com/38886749/89882833-6c9f0080-dbd8-11ea-829f-aaa779602db4.png">

**Comment by Desze** [comment]
> 
![Captura de pantalla de 2020-08-11 04-57-43](https://user-images.githubusercontent.com/69503074/89884948-e363db80-db8f-11ea-848a-639952245944.png)

**Comment by YnwaFawzy** [comment]
@Desze 
can you do a pprint before and after the profile_meta (line 78) to see if it was the reason

**Comment by Desze** [comment]
![Captura de pantalla de 2020-08-11 05-25-15](https://user-images.githubusercontent.com/69503074/89887105-5a4ea380-db93-11ea-8c66-77e77d6693b3.png)

**Comment by YnwaFawzy** [comment]
@Desze just add pprint("hello1") on line 76 
and pprint("hello2") on line 78

i just want to know where there error is getting thrown

**Comment by Desze** [comment]
~/InstagramOSINT$ python3 main.py --username idesze
  File "main.py", line 76
    pprint("hello1")
                   ^
IndentationError: unindent does not match any outer indentation level

**Comment by Desze** [comment]
:~/InstagramOSINT$ sudo python3 main.py --username desze
  File "main.py", line 77
    self.profile_meta = json.loads(more_data[3].string[21:].strip(';'))
                                                                      ^
IndentationError: unindent does not match any outer indentation level

**Comment by YnwaFawzy** [comment]
can you use this file 
[main.py 2.zip](https://github.com/sc1341/InstagramOSINT/files/5056507/main.py.2.zip)

**Comment by Desze** [comment]
working

**Comment by YnwaFawzy** [comment]
@Desze perfect , you can remove the two pprints in line 77 and 79 for cleaner ouput

**Comment by Chewbee** [comment]
You should commit this ;)

**Comment by YnwaFawzy** [comment]
why not

there you go guys , you can download it from here https://github.com/YnwaFawzy/InstagramOSINT

in case you have any other issues I'll be happy to help here or there as i believe the developer stopped supporting this repository.

have fun

**Comment by kaushalag29** [comment]
Please use my branch code "kaushalag29", I have raised the PR for this.
https://github.com/kaushalag29/InstagramOSINT

**Comment by F-2-0** [comment]
> Please use my branch code "kaushalag29" I have raised the PR for this.
> https://github.com/kaushalag29/InstagramOSINT

I used ur branch still the same prob

**Comment by F-2-0** [comment]
> why not
> 
> there you go guys , you can download it from here https://github.com/YnwaFawzy/InstagramOSINT
> 
> in case you have any other issues I'll be happy to help here or there as i believe the developer stopped supporting this repository.
> 
> have fun

Guyz use this worked for me

**Comment by kaushalag29** [comment]
> > Please use my branch code "kaushalag29" I have raised the PR for this.
> > https://github.com/kaushalag29/InstagramOSINT
> 
> I used ur branch still the same prob

Are you sure you downloaded from "kaushalag29" branch and not "master" branch.

**Comment by F-2-0** [comment]
> > > Please use my branch code "kaushalag29" I have raised the PR for this.
> > > https://github.com/kaushalag29/InstagramOSINT
> > 
> > I used ur branch still the same prob
> 
> Are you sure you downloaded from "kaushalag29" branch(checked out to kaushalag29) and not "master" branch.

Yes i am

**Comment by kaushalag29** [comment]
> > > > Please use my branch code "kaushalag29" I have raised the PR for this.
> > > > https://github.com/kaushalag29/InstagramOSINT
> > > 
> > > 
> > > I used ur branch still the same prob
> > 
> > 
> > Are you sure you downloaded from "kaushalag29" branch(checked out to kaushalag29) and not "master" branch.
> 
> Yes i am sure i used ur branch
> but nvm it worked when i use https://github.com/YnwaFawzy/InstagramOSINT this one

Bro! I checked, it's working for me.
Please check the output of `git branch` or trying checking out `git checkout kaushalag29` and then re-try.

**Comment by F-2-0** [comment]
> > > > > Please use my branch code "kaushalag29" I have raised the PR for this.
> > > > > https://github.com/kaushalag29/InstagramOSINT
> > > > 
> > > > 
> > > > I used ur branch still the same prob
> > > 
> > > 
> > > Are you sure you downloaded from "kaushalag29" branch(checked out to kaushalag29) and not "master" branch.
> > 
> > Yes i am sure i used ur branch
> > but nvm it worked when i use https://github.com/YnwaFawzy/InstagramOSINT this one
> 
> Bro! I checked, it's working for me.
> Please check the output of `git branch` or trying checking out `git checkout kaushalag29` and then re-try.

Np im using another one

**Comment by user333222** [comment]
> why not
> 
> there you go guys , you can download it from here https://github.com/YnwaFawzy/InstagramOSINT
> 
> in case you have any other issues I'll be happy to help here or there as i believe the developer stopped supporting this repository.
> 
> have fun

I still get the below error after using your updated version.

None
list index out of range
Username google not found

**Comment by YnwaFawzy** [comment]
@user333222  can you provide me with the command you wrote and a screenshot, because it works fine on my device.
![image](https://user-images.githubusercontent.com/38886749/100755893-17486280-3406-11eb-8d14-05d0893cd925.png)

**Comment by user333222** [comment]
> @user333222 can you provide me with the command you wrote and a screenshot, because it works fine on my device.
> ![image](https://user-images.githubusercontent.com/38886749/100755893-17486280-3406-11eb-8d14-05d0893cd925.png)

Im using the same command as you. 

kali@kali:~/Desktop/Scirpt/InstagramOSINT-master$ python3 main.py --username google

[*] Starting Scan on google
None
list index out of range
Username google not found
kali@kali:~/Desktop/Scirpt/InstagramOSINT-master$

**Comment by YnwaFawzy** [comment]
can you provide me with a screenshot please , also you're using the one here  https://github.com/YnwaFawzy/InstagramOSINT right ? , can you try to open the page normally in a browser to see if they consider you as a bot . and are you sure that you don't have any firewall that blocks the connection. 

try to edit the program to print out the html just to get more information about the error

**Comment by user333222** [comment]
Yes, i'm using the one you provided. ( https://github.com/YnwaFawzy/InstagramOSINT ) I downloaded it to my machine right from your github so I know its correct. I can open google and search fine (not a bot). What should i edit to print the HTML out? 

![image](https://user-images.githubusercontent.com/75276435/100761235-49cb6e80-33b8-11eb-94a2-05b5a7cf9e84.png)

**Comment by user333222** [comment]
> can you provide me with a screenshot please , also you're using the one here https://github.com/YnwaFawzy/InstagramOSINT right ? , can you try to open the page normally in a browser to see if they consider you as a bot . and are you sure that you don't have any firewall that blocks the connection.
> 
> try to edit the program to print out the html just to get more information about the error

Above^

**Comment by YnwaFawzy** [comment]
on line 57 where soup is created,  write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start

**Comment by user333222** [comment]
its in the zip, file called test. was a lot to past here

[test.zip](https://github.com/sc1341/InstagramOSINT/files/5624009/test.zip)

**Comment by user333222** [comment]
> on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start

its in the zip, file called test. was a lot to past here
[test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)

**Comment by kaushalag29** [comment]
@

> > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> 
> its in the zip, file called test. was a lot to past here
> [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)

Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT

**Comment by user333222** [comment]
> @
> 
> > > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> > 
> > 
> > its in the zip, file called test. was a lot to past here
> > [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)
> 
> Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT

I had the same issue with yours too, so not sure.

**Comment by kaushalag29** [comment]
> > @
> > > > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> > > 
> > > 
> > > its in the zip, file called test. was a lot to past here
> > > [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)
> > 
> > 
> > Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT
> 
> I had the same issue with yours too, so not sure.

I have merged the code from "kaushalag29" branch to "master" branch, today itself. I don't know when you last tried with my repo. Please git pull before executing.

**Comment by user333222** [comment]
> > > @
> > > > > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> > > > 
> > > > 
> > > > its in the zip, file called test. was a lot to past here
> > > > [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)
> > > 
> > > 
> > > Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT
> > 
> > 
> > I had the same issue with yours too, so not sure.
> 
> I have merged the code from "kaushalag29" branch to "master" branch, today itself. I don't know when you last tried with my repo. Please git pull before executing.

I downloaded it directly from your github page. Same issue still

**Comment by kaushalag29** [comment]
> > > > @
> > > > > > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> > > > > 
> > > > > 
> > > > > its in the zip, file called test. was a lot to past here
> > > > > [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)
> > > > 
> > > > 
> > > > Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT
> > > 
> > > 
> > > I had the same issue with yours too, so not sure.
> > 
> > 
> > I have merged the code from "kaushalag29" branch to "master" branch, today itself. I don't know when you last tried with my repo. Please git pull before executing.
> 
> I downloaded it directly from your github page. Same issue still

That's what I am asking, at what time you downloaded it? Plz download it again and try.

**Comment by user333222** [comment]
> > > > > @
> > > > > > > on line 57 where soup is created, write "print(soup)" after one line , and send the results , this will show the html source code and if the server is denying the access for a start
> > > > > > 
> > > > > > 
> > > > > > its in the zip, file called test. was a lot to past here
> > > > > > [test.zip](https://github.com/sc1341/InstagramOSINT/files/5624016/test.zip)
> > > > > 
> > > > > 
> > > > > Meanwhile you can try my repo https://github.com/kaushalag29/InstagramOSINT
> > > > 
> > > > 
> > > > I had the same issue with yours too, so not sure.
> > > 
> > > 
> > > I have merged the code from "kaushalag29" branch to "master" branch, today itself. I don't know when you last tried with my repo. Please git pull before executing.
> > 
> > 
> > I downloaded it directly from your github page. Same issue still
> 
> That's what I am asking, at what time you downloaded it? Plz download it again and try.

I just re-downloaded it from your page now mate

**Comment by YnwaFawzy** [comment]
ok , so this is really weird, let's try to go through it step by step, you might know why this is happening.

if you go through the source code that you sent , you will see that it asks you to login to Instagram , which I am not sure if this is a new update from their side or something wrong from yours. 
you can verify that by checking the <title> login Instagram </title> , also you can see this link instagram.com/accounts/login?next=/google/ , which asks you to login first, so I accessed the link and logged in and it worked fine.

I've tried to check using curl request without editing the user agent , and it worked too ( the source code was matching the /google/ profile).

so the question is , are you accessing a newer version of Instagram web that probably didn't reflect to the servers in my region , I am not sure.

but just to confirm that , can you send me the output of this command  "curl -X GET https://instagram.com/google/", and try to change the user agent in the tool it might work with you

**Comment by user333222** [comment]
Thats

> ok , so this is really weird, let's try to go through it step by step, you might know why this is happening.
> 
> if you go through the source code that you sent , you will see that it asks you to login to Instagram , which I am not sure if this is a new update from their side or something wrong from yours.
> you can verify that by checking the <title> login Instagram </title> , also you can see this link instagram.com/accounts/login?next=/google/ , which asks you to login first, so I accessed the link and logged in and it worked fine.
> 
> I've tried to check using curl request without editing the user agent , and it worked too ( the source code was matching the /google/ profile).
> 
> so the question is , are you accessing a newer version of Instagram web that probably didn't reflect to the servers in my region , I am not sure.
> 
> but just to confirm that , can you send me the output of this command "curl -X GET https://instagram.com/google/", and try to change the user agent in the tool it might work with you

Thats really weird, I see what your saying. I did a little research on it, and it seems that Instagram is now not allowing users to view profiles without logging in it seems. 

If I login, will the script work, or will it still require manual sign in each request because it doesn't know my login. If its stored in cookeis will i work? 

curl -X GET https://instagram.com/google doesn't show anything in console for me. nothing is returned.

**Comment by YnwaFawzy** [comment]
sorry , try this curl -X GET https://instagram.com/google/

**Comment by user333222** [comment]
> sorry , try this curl -X GET https://instagram.com/google/

curl -X GET https://instagram.com/google/
still nothing is returned

**Comment by YnwaFawzy** [comment]
no problem, i'll just add the login functionality to the code , test it with private profiles and upload the solution, i'll ping you when i am done :D

**Comment by user333222** [comment]
> no problem, i'll just add the login functionality to the code , test it with private profiles and upload the solution, i'll ping you when i am done :D

Woot! Your awesome

**Comment by YnwaFawzy** [comment]
@user333222 ok , i didn't expect it to be that fast , but check https://github.com/kaushalag29/InstagramOSINT again , and change "username_here" to your username and "passwordhere" to your password (keep the <>) .

this will add the ability to check for private profiles too ( i checked it on one profile and it worked !)

can you check it and confirm if it works

**Comment by YnwaFawzy** [comment]
> @user333222 ok , i didn't expect it to be that fast , but check https://github.com/kaushalag29/InstagramOSINT again , and change "username_here" to your username and "password_here" to your password (keep the <>) .
> 
> this will add the ability to check for private profiles too ( i checked it on one profile and it worked !)
> 
> can you check it and confirm if it works

my bad , i meant this one https://github.com/YnwaFawzy/InstagramOSINT

**Comment by user333222** [comment]
I have no account to test, I created one and they want to take 24 hours to review it. So..... I will update you once I can try

> > @user333222 ok , i didn't expect it to be that fast , but check https://github.com/kaushalag29/InstagramOSINT again , and change "username_here" to your username and "password_here" to your password (keep the <>) .
> > this will add the ability to check for private profiles too ( i checked it on one profile and it worked !)
> > can you check it and confirm if it works
> 
> my bad , i meant this one https://github.com/YnwaFawzy/InstagramOSINT

I have no account to test, I created one and they want to take 24 hours to review it. So..... I will update you once I can try it. But it seems as you already tested it yourself.

**Comment by YnwaFawzy** [comment]
sure tyt , waiting for your update

**Comment by mathiskaddouri** [comment]
@YnwaFawzy 
I have just tried your attempt to login on your fork.
Unfortunatly it's seems not working, I have an keyerror when using ```csrf = response.cookies['csrftoken']```, there is no csrftoken cookie in the response.

**Comment by Venkateshvenki404224** [comment]
![Screenshot 2020-12-15 102823](https://user-images.githubusercontent.com/75518037/102173130-5bd10500-3ec0-11eb-80df-7e499ac2aee4.png)
I'am getting this above error
please help

**Comment by YnwaFawzy** [comment]
@Venkateshvenki404224 python3 main.py

**Comment by Venkateshvenki404224** [comment]
![python](https://user-images.githubusercontent.com/75518037/102569224-0fc5d080-410b-11eb-8296-a632a225fbfc.png)
I have the latest version of python as mentioned above image
Even though i am getting the error

**Comment by San4ito** [comment]
> ![Screenshot 2020-12-15 102823](https://user-images.githubusercontent.com/75518037/102173130-5bd10500-3ec0-11eb-80df-7e499ac2aee4.png)
> I'am getting this above error
> please help

Me too. I have python3.7 and get the same problem

**Comment by YnwaFawzy** [comment]
@San4ito oh this is the latest version ,yea i wasn't sure it was working.

I'll check the error and update you guys.

**Comment by San4ito** [comment]
@YnwaFawzy thanks a lot!!

**Comment by kelvindias** [comment]
> @Desze
> So i checked your profile on the web browser , and strangely the description field doesn't exist ( as the json schema that should represent your profile <script type="application/ld+json"> ).
> 
> a quick fix is i checked if the json schema exist by adding
> 
> ```
>             if( description is not None):
>               self.description = json.loads(description.string)
> ```
> 
> and then i divided the output into two parts ,the basic one and the description
> 
> `
> self.profile_data = {"Username": self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['username'],
> "Followers": self.text[0], "Following": self.text[2], "Posts": self.text[4],
> "Bio": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['biography']),
> "profile_pic_url": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'profile_pic_url_hd']),
> "is_business_account": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_business_account']),
> "connected_to_fb": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'connected_fb_page']),
> "externalurl": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['external_url']),
> "joined_recently": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_joined_recently']),
> "business_category_name": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'business_category_name']),
> "is_private": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_private']),
> "is_verified": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_verified'])}
> 
> `
> 
> and for the description if found
> `if (description is not None): { "Profile name": self.description['name'], "URL": self.description['mainEntityofPage']['@id'], }`
> 
> it should be working fine now , you can get the new file
> [main.py.zip](https://github.com/sc1341/InstagramOSINT/files/5056036/main.py.zip)

it works! thanks

**Comment by w1th0ut** [comment]
> @Desze
> So i checked your profile on the web browser , and strangely the description field doesn't exist ( as the json schema that should represent your profile <script type="application/ld+json"> ).
> 
> a quick fix is i checked if the json schema exist by adding
> 
> ```
>             if( description is not None):
>               self.description = json.loads(description.string)
> ```
> 
> and then i divided the output into two parts ,the basic one and the description
> 
> `
> self.profile_data = {"Username": self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['username'],
> "Followers": self.text[0], "Following": self.text[2], "Posts": self.text[4],
> "Bio": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['biography']),
> "profile_pic_url": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'profile_pic_url_hd']),
> "is_business_account": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_business_account']),
> "connected_to_fb": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'connected_fb_page']),
> "externalurl": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['external_url']),
> "joined_recently": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_joined_recently']),
> "business_category_name": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'business_category_name']),
> "is_private": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_private']),
> "is_verified": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_verified'])}
> 
> `
> 
> and for the description if found
> `if (description is not None): { "Profile name": self.description['name'], "URL": self.description['mainEntityofPage']['@id'], }`
> 
> it should be working fine now , you can get the new file
> [main.py.zip](https://github.com/sc1341/InstagramOSINT/files/5056036/main.py.zip)

wow working, thanks!

**Comment by cyclelogic** [comment]
I have the same issue. I cloned the repo today. 

(root💀tlosint)-[/opt/InstagramOSINT]
└─# python3 --version                                                      
Python 3.8.6
┌──(root💀tlosint)-[/opt/InstagramOSINT]
└─# pip3 install -r requirements.txt                                       
Requirement already satisfied: argparse in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 1)) (1.4.0)
Requirement already satisfied: bs4 in /usr/local/lib/python3.8/dist-packages (from -r requirements.txt (line 2)) (0.0.1)
Requirement already satisfied: requests in /usr/lib/python3/dist-packages (from -r requirements.txt (line 3)) (2.24.0)
Requirement already satisfied: beautifulsoup4 in /usr/lib/python3/dist-packages (from bs4->-r requirements.txt (line 2)) (4.9.3)
Requirement already satisfied: soupsieve>1.2 in /usr/lib/python3/dist-packages (from beautifulsoup4->bs4->-r requirements.txt (line 2)) (2.0.1)
┌──(root💀tlosint)-[/opt/InstagramOSINT]

# python3 main.py --username hoopscoach123                               
                                                                           
Traceback (most recent call last):
  File "main.py", line 284, in <module>
    main()
  File "main.py", line 280, in main
    osint = InstagramOSINT(username=args.username[0], downloadPhotos=args.downloadPhotos)
  File "main.py", line 58, in __init__
    csrf = response.cookies['csrftoken']
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 328, in __getitem__
    return self._find_no_duplicates(name)
  File "/usr/lib/python3/dist-packages/requests/cookies.py", line 399, in _find_no_duplicates
    raise KeyError('name=%r, domain=%r, path=%r' % (name, domain, path))
KeyError: "name='csrftoken', domain=None, path=None"

**Comment by cybot-spec** [comment]
Osintgram is showing  incorrect username when it attempted to login. pls help to solve this problem

**Comment by C4l1b3r** [comment]
> @Desze
> So i checked your profile on the web browser , and strangely the description field doesn't exist ( as the json schema that should represent your profile <script type="application/ld+json"> ).
> 
> a quick fix is i checked if the json schema exist by adding
> 
> ```
>             if( description is not None):
>               self.description = json.loads(description.string)
> ```
> 
> and then i divided the output into two parts ,the basic one and the description
> 
> `
> self.profile_data = {"Username": self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['username'],
> "Followers": self.text[0], "Following": self.text[2], "Posts": self.text[4],
> "Bio": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['biography']),
> "profile_pic_url": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'profile_pic_url_hd']),
> "is_business_account": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_business_account']),
> "connected_to_fb": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'connected_fb_page']),
> "externalurl": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['external_url']),
> "joined_recently": str(self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'is_joined_recently']),
> "business_category_name": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user'][
> 'business_category_name']),
> "is_private": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_private']),
> "is_verified": str(
> self.profile_meta['entry_data']['ProfilePage'][0]['graphql']['user']['is_verified'])}
> 
> `
> 
> and for the description if found
> `if (description is not None): { "Profile name": self.description['name'], "URL": self.description['mainEntityofPage']['@id'], }`
> 
> it should be working fine now , you can get the new file
> [main.py.zip](https://github.com/sc1341/InstagramOSINT/files/5056036/main.py.zip)

This worked thank you

**Comment by Amroth898** [comment]
Still not working for me, I get 

[*] Starting Scan on ****
None
list index out of range
Username **** not found

**Comment by jeatic** [comment]
Yes, I have the same problem. I don't know how to fix it, I have tested with all the main previously gaven. Do you have a solution?

**Comment by YnwaFawzy** [comment]
check https://github.com/Datalux/Osintgram

**Comment by Brewas** [comment]
Hello. I'm having an issue, when I enter the command: python3 main.py [targeted instagram account] it shows me an error:
Traceback (most recent call last):
  File "/home/aidlau/Osintgram/main.py", line 21, in <module>
    from banner import banner
ImportError: cannot import name 'banner' from 'banner' (/home/ew4fg5we/Osintgram/myenv/lib/python3.11/site-packages/banner/__init__.py)

**Comment by YnwaFawzy** [comment]
i couldn't see this sentence in osintgram 
 from banner import banner
where did you get it ?

**Comment by Brewas** [comment]
It's located in main.py line 21, where all the imports are.

**Comment by YnwaFawzy** [comment]
line 21 one from https://github.com/Datalux/Osintgram/blob/master/main.py has the following 

` pc.printout("\nVersion 1.1 - Developed by Giuseppe Criscione\n\n", pc.YELLOW)`

**Comment by Brewas** [comment]
Okay, so my Osintgram directory looks like this:
![Screenshot_2023-03-26_18-13-54](https://user-images.githubusercontent.com/125255853/227785778-b79680af-3734-4174-94b4-fa309062ba6b.png)
I replaced main.py with new one (https://github.com/Datalux/Osintgram/blob/master/main.py)
But I still seem to get errors:
Traceback (most recent call last):
  File "/home/ddtfvygbu/Osintgram/main.py", line 3, in <module>
    from src.Osintgram import Osintgram
  File "/home/ddtfvygbu/Osintgram/src/Osintgram.py", line 13, in <module>
    from geopy.geocoders import Nominatim
ModuleNotFoundError: No module 
Maybe I'm doing something wrong? Downloading wrong file, not putting them where they need to be?
Thanks for help.

**Comment by YnwaFawzy** [comment]
you need to install geocoders module

**Comment by Brewas** [comment]
I have already installed geocoders module, after I run python3 main.py [targeted username] it shows me this error:



Attempt to login...
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/aidlau/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 523, in _call_api
    response = self.opener.open(req, timeout=self.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 525, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 634, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 563, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aidlau/Osintgram/main.py", line 121, in <module>
    api = Osintgram(args.id, args.file, args.json, args.command, args.output, args.cookies)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidlau/Osintgram/src/Osintgram.py", line 48, in __init__
    self.setTarget(target)
  File "/home/aidlau/Osintgram/src/Osintgram.py", line 61, in setTarget
    self.following = self.check_following()
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidlau/Osintgram/src/Osintgram.py", line 1159, in check_following
    return self.api._call_api(endpoint)['user_detail']['user']['friendship_status']['following']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/aidlau/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/client.py", line 527, in _call_api
    ErrorHandler.process(e, error_response)
  File "/home/aidlau/Osintgram/venv/lib/python3.11/site-packages/instagram_private_api/errors.py", line 135, in process
    raise ClientError(error_msg, http_error.code, error_response)
instagram_private_api.errors.ClientError: Not Found

**Comment by YnwaFawzy** [comment]
are you sure the username exists ? i can see  HTTP Error 404: Not Found .

which username did you try

**Comment by Brewas** [comment]
So i put in my own account username (the same username I saved in credentials.ini file) as targeted username and it seemed to work. When I try any other username, it doesn't. So does this mean, that the main.py only works on my own username?

**Comment by Jlb15** [comment]
@Brewas hey man I actually have the same kind of problem, I put my username (the one that is in credential file) and it works but when I put a different user it stops working and it appears me as “user not found”

**Comment by Jlb15** [comment]
@YnwaFawzy Can you help me?

**Comment by YnwaFawzy** [comment]
try to ask the guys at osintgram, i think they might help you better as i didn't check their code

**Comment by Gaurav60419430** [comment]
how so i fix this 
![Uploading Screenshot 2024-01-09 081451.png…]()

**Comment by Gaurav60419430** [comment]
how do i fix this @Cybrarist 
![Screenshot 2024-01-09 081451](https://github.com/sc1341/InstagramOSINT/assets/64767197/877f9b84-2a10-4652-8f61-79c26a5391a4)

**Comment by Cybrarist** [comment]
@Gaurav60419430 can you check with this tool https://github.com/Datalux/Osintgram
i think this repo is not maintained any more.

**Comment by Gaurav60419430** [comment]
how to do it plz tell me

**Comment by Gaurav60419430** [comment]
how do i do it i have follow every instructions but still invalid target 

can u please tell in step by step manner its important for my course
assignment

**Comment by Adsf324** [comment]
I have the same problem as you. What is the solution to this problem?

Run a command: info                                                                                                                     
Error parsing error response: Expecting value: line 1 column 1 (char 0)
Not Found
Oops... xlxx_ non exist, please enter a valid username.
![Screenshot_2024-03-07_23_08_05](https://github.com/sc1341/InstagramOSINT/assets/162663041/1cfb3e7d-1f71-44dc-8414-f6de0f6ef08a)
@Cybrarist
